### ISSUE TITLE
VL53L1X Experience

### ISSUE THREAD

**Issue by HamzaHajeir** [trlafleur/Tasmota-Tank-Sensor#1]
Hi there,

I'm wondering whether usage of VL53L1X is reliable for measuring water tanks levels or not. I had experience where at night it gives false measurements (ghost objects), therefore was unuseful for me.

Have you went through this issue?

With Thanks,
Hamza

**Comment by trlafleur** [comment]
i have not tested with water, only fuel oil, i do take 32 samples to remove
odd readings

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by HamzaHajeir** [comment]
I see that, thank you.

We had good experience with diesel tanks regarding accuracy all over the
day-night, despite being affected and decapped/damaged.

But had issues with water for its transparency, especially at night.

**Comment by trlafleur** [comment]
if you look at my photos, you will see that I have a Lexan window between
the sensor and fuel oil...

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by HamzaHajeir** [comment]
I see that.

Thank you for your response. I appreciate that.

Best regards,
Hamza
